name: lensforge
description: "LensForge is a Flutter mobile application that scans real-world objects using device cameras and generates 3D models. The app features a sleek, modern UI with advanced scanning capabilities and 3D model interaction."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/lensforge_logo.png